CatalogoPeliculasEquipo/Models/Pelicula.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace CatalogoPeliculasEquipo.Models
{
    public partial class Pelicula
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Año { get; set; }
        public string Categoria { get; set; }
        public string Clasificacion { get; set; }
        public string Pais { get; set; }
        public string Sinopsis { get; set; }
        public int Idproductor { get; set; }

        public virtual Productor IdproductorNavigation { get; set; }
    }
}

CatalogoPeliculasEquipo/Areas/Admin/Controllers/PeliculasController.cs
using CatalogoPeliculasEquipo.Areas.Admin.Models;
using CatalogoPeliculasEquipo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CatalogoPeliculasEquipo.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    //[Authorize(Roles = "Administrador")]
    public class PeliculasController : Controller
    {
        public peliculasContext Context { get; }
        public IWebHostEnvironment Host { get; }

        public PeliculasController(peliculasContext context, IWebHostEnvironment host)
        {
            Context = context;
            Host = host;
        }
        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<Pelicula> p = Context.Peliculas.OrderBy(x => x.Nombre);
            return View(p);
        }
        [Authorize(Roles = "Administrador")]
        public IActionResult Agregar()
        {
            return View(new PeliculasIndexViewModel
            {
                Productores = Context.Productors.OrderBy(x => x.Nombre)
            });
        }
        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public IActionResult Agregar(PeliculasIndexViewModel vm, IFormFile foto)
        {   if (Context.Peliculas.Any(x => x.Nombre == vm.Peliculas.Nombre))
            {
                ModelState.AddModelError("", "Ya existe una película con el mismo nombre");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
            
            if (string.IsNullOrWhiteSpace(vm.Peliculas.Nombre))
            {
                ModelState.AddModelError("", "El nombre de la película no puede ir vacío");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
            if (string.IsNullOrWhiteSpace(vm.Peliculas.Año))
            {
                ModelState.AddModelError("", "El película de la pelicula está vacío");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
            if (string.IsNullOrWhiteSpace(vm.Peliculas.Categoria))
            {
                ModelState.AddModelError("", "La categoría de la película está vacía");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
            if (string.IsNullOrWhiteSpace(vm.Peliculas.Clasificacion))
            {
                ModelState.AddModelError("", "La clasificación de la película está vacía");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
            if (string.IsNullOrWhiteSpace(vm.Peliculas.Pais))
            {
                ModelState.AddModelError("", "El país de la película está vacío");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
            if (string.IsNullOrWhiteSpace(vm.Peliculas.Sinopsis))
            {
                ModelState.AddModelError("", "La sinopsis de la película está vacía");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
            if (vm.Peliculas.Idproductor<=0)
            {
                ModelState.AddModelError("", "Seleccione una productora para poder continuar");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
           
            if (foto != null)
            {
                if (foto.ContentType != "image/jpeg")
                {
                    ModelState.AddModelError("", "Solo se permite la carga de archivos JPG");
                    vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                    return View(vm);
                }
                if (foto.Length > 1024 * 1024 * 5)
                {
                    ModelState.AddModelError("", "No se permite la carga de archivos mayores a 5MB");
                    vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                    return View(vm);
                }
            }
            Context.Add(vm.Peliculas);
            Context.SaveChanges();
            if (foto != null)
            {
                var path = Host.WebRootPath+"/imgs_peliculas/"+vm.Peliculas.Id + "_peli.jpg";
                FileStream fs = new FileStream(path, FileMode.Create);
                foto.CopyTo(fs);
                fs.Close();
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Modificar(int id)
        {
            Pelicula p = Context.Peliculas.FirstOrDefault(x => x.Id == id);
         
            if (p == null)
            {
                return RedirectToAction("Index");
            }
            PeliculasIndexViewModel vm = new PeliculasIndexViewModel
            {
                Peliculas = p,
                Productores = Context.Productors.OrderBy(x => x.Nombre)
            };
            return View(vm);
        }
        [HttpPost]
        public IActionResult Modificar(PeliculasIndexViewModel vm, IFormFile foto)
        {


            var p = Context.Peliculas.FirstOrDefault(x => x.Id == vm.Peliculas.Id);
            if (p == null)
            {
                return RedirectToAction("Index");
            }
           
            if (Context.Peliculas.Any(x => x.Nombre == vm.Peliculas.Nombre && x.Id!=vm.Peliculas.Id))
            {
                ModelState.AddModelError("", "Ya existe una película con el mismo nombre");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }

            if (string.IsNullOrWhiteSpace(vm.Peliculas.Nombre))
            {
                ModelState.AddModelError("", "El nombre de la película no puede ir vacío");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
            if (string.IsNullOrWhiteSpace(vm.Peliculas.Año))
            {
                ModelState.AddModelError("", "El película de la pelicula está vacío");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
            if (string.IsNullOrWhiteSpace(vm.Peliculas.Categoria))
            {
                ModelState.AddModelError("", "La categoría de la película está vacía");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
            if (string.IsNullOrWhiteSpace(vm.Peliculas.Clasificacion))
            {
                ModelState.AddModelError("", "La clasificación de la película está vacía");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
            if (string.IsNullOrWhiteSpace(vm.Peliculas.Pais))
            {
                ModelState.AddModelError("", "El país de la película está vacío");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
            if (string.IsNullOrWhiteSpace(vm.Peliculas.Sinopsis))
            {
                ModelState.AddModelError("", "La sinopsis de la película está vacía");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }
            if (vm.Peliculas.Idproductor <= 0)
            {
                ModelState.AddModelError("", "Seleccione una productora para poder continuar");
                vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                return View(vm);
            }

            if (foto != null)
            {
                if (foto.ContentType != "image/jpeg")
                {
                    ModelState.AddModelError("", "Solo se permite la carga de archivos JPG");
                    vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                    return View(vm);
                }
                if (foto.Length > 1024 * 1024 * 5)
                {
                    ModelState.AddModelError("", "No se permite la carga de archivos mayores a 5MB");
                    vm.Productores = Context.Productors.OrderBy(x => x.Nombre);
                    return View(vm);
                }
            }
            p.Nombre = vm.Peliculas.Nombre;
            p.Año = vm.Peliculas.Año;
            p.Categoria = vm.Peliculas.Categoria;
            p.Clasificacion = vm.Peliculas.Clasificacion;
            p.Pais = vm.Peliculas.Pais;
            p.Sinopsis = vm.Peliculas.Sinopsis;
            p.Idproductor = vm.Peliculas.Idproductor;
            
           
     Context.Update(p);
            Context.SaveChanges();
            if (foto != null)
            {
                var path = Host.WebRootPath + "/imgs_peliculas/" + vm.Peliculas.Id + "_peli.jpg";
                FileStream fs = new FileStream(path, FileMode.Create);
                foto.CopyTo(fs);
                fs.Close();
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            Pelicula raza = Context.Peliculas.FirstOrDefault(x => x.Id == id);
            if (raza == null)
            {
                return RedirectToAction("Index");
            }
            return View(raza);
        }

        [HttpPost]
        public IActionResult Eliminar(Pelicula vm)
        {
            Pelicula p = Context.Peliculas.FirstOrDefault(x => x.Id == vm.Id);
          
            if (p == null)
            {

CatalogoPeliculasEquipo/Areas/Admin/Views/Peliculas/Agregar.cshtml
@model CatalogoPeliculasEquipo.Areas.Admin.Models.PeliculasIndexViewModel
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment env
@{ ViewData["Title"] = "Agregar";
    Layout = "_LayoutAdmin"; }

<section class="botonEsquina" @*style=""*@>
  
    <a id="botonRegresar" href="~/Admin/Peliculas">
        ↩
    </a>
</section>
<div id="crudM">
    <form method="post" asp-area="Admin" asp-controller="Peliculas" asp-action="Agregar" enctype="multipart/form-data">
        <div id="crudAdm">
            <label >Nombre:</label>
            <input type="text" asp-for="Peliculas.Nombre" required ><br><br>
            <label >Año:</label>
            <input type="text" asp-for="Peliculas.Año" required><br><br>
            <label >Categoría:</label>
            <input type="text" asp-for="Peliculas.Categoria" required><br><br>
            <label >Clasificación:</label>
            <input type="text" asp-for="Peliculas.Clasificacion" required><br><br>
            <label >País:</label>
            <input type="text" asp-for="Peliculas.Pais" required><br><br>
            <label >Sinopsis:</label>
            <textarea asp-for="Peliculas.Sinopsis" required></textarea><br /><br>
            <select required asp-for="Peliculas.Idproductor" asp-items="@(new SelectList(Model.Productores, "Id", "Nombre"))">
                <option selected value="">Selecciona una productora</option>
            </select><br><br>
           
            <h4 id="MensajeDeError"  >
                @Html.ValidationSummary()
            </h4>
        </div>
        <div id="crudImg">
            <img id="imagePreview" src="~/imgs/nophoto2.jpg" alt="Vista previa de la imagen">
            <input type="file" id="fileImage" name="foto" accept="image/jpeg">
        </div>
        <input type="submit" value="Agregar ">
    </form>

</div>
<br class="clear" />

<script>
    function mostrarImagen(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                document.querySelector('#imagePreview').src = e.target.result;
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    document.querySelector("#fileImage").addEventListener("change", event => {
        mostrarImagen(event.target)
    });</script>

CatalogoPeliculasEquipo/Areas/Admin/Views/Peliculas/Eliminar.cshtml
@model CatalogoPeliculasEquipo.Models.Pelicula;
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment env
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers

@{ ViewData["Title"] = "Eliminar";
    Layout = "_LayoutAdmin"; }

<section class="botonEsquina">
    <a id="botonRegresar" href="~/Admin/Peliculas">
        ↩
    </a>
</section>
<div id="crudM" style=" display: block; width: 50%; margin: auto; left: 20%; position: relative;">
    <div id="crudImg" style="top: 15%; width: 100%; display: block; position: absolute;">
        @if (System.IO.File.Exists($"{env.WebRootPath}/imgs_peliculas/{Model.Id}_peli.jpg"))
        {
<img style="color:white" id="imagePreview" src="~/imgs_peliculas/@(Model.Id)_peli.jpg" alt="Vista previa de la imagen"> }
else
{
<img style="color:white" id="imagePreview" src="~/imgs/nophoto2.jpg" alt="Vista previa de la imagen">}
    </div>
    <p style="width: 100%; text-align: center; font-size: larger; display: block; position: absolute;">¿Seguro de eliminar la película @(Model.Nombre)?</p>
    <p>
        @Html.ValidationSummary()
    </p>
    <form method="post" asp-area="Admin" asp-controller="Peliculas" asp-action="Eliminar">
        <input asp-for="Nombre" value="@(Model.Nombre)" hidden />
        <input asp-for="Id" value="@(Model.Id)" hidden />
        <input style="width:100%" type="submit" value="Eliminar">
    </form>

</div>


<br class="clear" />

CatalogoPeliculasEquipo/Areas/Admin/Views/Peliculas/Index.cshtml
@model IEnumerable<CatalogoPeliculasEquipo.Models.Pelicula>
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment env
@{
    ViewData["Title"] = "Index";
    Layout = "_LayoutAdmin";
}
<section class="areadeAgregar">
    @*<h1 style="display: block; position: absolute; font-size: 30px; padding: 0; margin: 0;">Administrar las peliculas </h1>*@
    @if (User.IsInRole("Administrador"))
    {
        <a id="botonAgregar" href="~/Admin/Peliculas/Agregar">
            Añadir ➕
        </a>}

</section>
<div id="pelis">
    @foreach (var p in Model)
    {
    <div class="infoPeliConFoto">
        <a class="imgPelicula" @*href="~/pelicula/@p.Nombre.Replace(" ","-").ToLower()"*@>
            @if (System.IO.File.Exists($"{env.WebRootPath}/imgs_peliculas/{p.Id}_peli.jpg"))
            {
                <img src="~/imgs_peliculas/@(p.Id)_peli.jpg" alt="@p.Nombre"> }
            else
            {
                <img src="~/imgs/nophoto2.jpg" alt="@p.Nombre">}

        </a>
        <p>@p.Nombre</p>
        <div class="botones">
            <a href="~/Admin/Peliculas/Modificar/@(p.Id)" class="btnEditar">✏️ Editar</a>
            <a href="~/Admin/Peliculas/Eliminar/@(p.Id)" class="btnBorrar">🗑️Eliminar</a>
        </div>
    </div>}
</div>

CatalogoPeliculasEquipo/Areas/Admin/Views/Peliculas/Modificar.cshtml
@model CatalogoPeliculasEquipo.Areas.Admin.Models.PeliculasIndexViewModel
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment env
@{ ViewData["Title"] = "Modificar";
    Layout = "_LayoutAdmin"; }

<section class="botonEsquina">

    <a id="botonRegresar" href="~/Admin/Peliculas">
        ↩
    </a>
</section>
<div id="crudM">
    <form method="post" asp-area="Admin" asp-controller="Peliculas" asp-action="Modificar" enctype="multipart/form-data">
        <div id="crudAdm">
            <input asp-for="Peliculas.Id" hidden />
            <label>Nombre:</label>
            <input type="text" asp-for="Peliculas.Nombre" required><br><br>
            <label>Año:</label>
            <input type="text" asp-for="Peliculas.Año" required><br><br>
            <label>Categoría:</label>
            <input type="text" asp-for="Peliculas.Categoria" required><br><br>
            <label>Clasificación:</label>
            <input type="text" asp-for="Peliculas.Clasificacion" required><br><br>
            <label>País:</label>
            <input type="text" asp-for="Peliculas.Pais" required><br><br>
            <label>Sinopsis:</label>
            <textarea asp-for="Peliculas.Sinopsis" required></textarea><br /><br>
            <select required asp-for="Peliculas.Idproductor" asp-items="@(new SelectList(Model.Productores, "Id", "Nombre"))">
                <option selected value="">Selecciona una productora</option>
            </select><br><br>

            <h4 id="MensajeDeError">
                @Html.ValidationSummary()
            </h4>
        </div>
        <div id="crudImg">
            @if (System.IO.File.Exists($"{env.WebRootPath}/imgs_peliculas/{Model.Peliculas.Id}_peli.jpg"))
            {
    <img id="imagePreview" src="~/imgs_peliculas/@(Model.Peliculas.Id)_peli.jpg" alt="Vista previa de la imagen"> }
                else
                {
    <img id="imagePreview" src="~/imgs/nophoto2.jpg" alt="Vista previa de la imagen">            }
            <input type="file" id="fileImage" name="foto" accept="image/jpeg">
        </div>
        <input type="submit" value="Modificar">
    </form>

</div>
<br class="clear" />

<script>function mostrarImagen(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                document.querySelector('#imagePreview').src = e.target.result;
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    document.querySelector("#fileImage").addEventListener("change", event => {
        mostrarImagen(event.target)
    });</script>